'''
    This python file uses test data of the SUMO simulation
    consequently the data are not generated by us. We used it to
    do a first data evaluation.
    This file prepares the data.


'''

# --------------------------------------------- DataPrep_emission -------------------------------------------

#Imports
import pandas as pd

#Read data
df=pd.read_excel("/Users/emily/Desktop/emission_excel.xlsx")
#print(df.head(10))

#Filter truck data (HBEFA3/HDV)
print(df[ (df.eclass.eq('HBEFA3/HDV'))])

#Save data
ze=df[ (df.eclass.eq('HBEFA3/HDV'))]
ze.to_excel("/Users/emily/Desktop/Zwischenergebnis.xlsx")

#Show typically metrics
print(ze.describe())

#Show missing values (nan, NaN, "")
print(ze.isnull().sum())

#Control datatypes
print(ze.dtypes)

#Save data
ze.to_excel("/Users/emily/Desktop/Prepared_Emission.xlsx")
