'''
    This python file uses test data of the SUMO simulation
    consequently the data are not generated by us.
    In this file we transform the emission.xml into a dataframe.


'''

# --------------------------------------------- ReadXMLemission -------------------------------------------

#Imports
import pandas as pd
import xml.etree.ElementTree as ET

root = ET.parse('/Users/emily/PROJECTS/FleetAnalytics/data/emission_output_SMALL.xml').getroot()
#root = ET.parse('/Users/emily/PROJECTS/FleetAnalytics/data/emission_output.xml').getroot()

df = pd.DataFrame(columns=["timestep", "vehicle_ID", "eclass", "CO2", "CO", "HC", "NOx","PMx", "fuel","electricity", "noise","route", "type","waiting", "lane","pos", "speed","angle", "x","y"])

for type_tag in root.findall('timestep'):
    var_timestep = type_tag.get('time')
    #print("Timestep: ", var_timestep)

    for type_vehicle in type_tag.findall('vehicle'):
        vehicle_ID = type_vehicle.get('id')
        #print("Vehicle ID: ", vehicle_ID)

        var_eclass = type_vehicle.get('eclass')
        #print("Vehicle eclass: ", var_eclass)
        var_CO2 = type_vehicle.get('CO2')
        var_CO = type_vehicle.get('CO')
        var_HC = type_vehicle.get('HC')
        var_NOx = type_vehicle.get('NOx')
        var_PMx = type_vehicle.get('PMx')
        var_fuel = type_vehicle.get('fuel')
        var_electricity = type_vehicle.get('electricity')
        var_noise = type_vehicle.get('noise')
        var_route = type_vehicle.get('route')
        var_type = type_vehicle.get('type')
        var_waiting = type_vehicle.get('waiting')
        var_lane = type_vehicle.get('lane')
        var_pos = type_vehicle.get('pos')
        var_speed = type_vehicle.get('speed')
        var_angle = type_vehicle.get('angle')
        var_x = type_vehicle.get('x')
        var_y = type_vehicle.get('y')

        df = df.append({
            "timestep": var_timestep,
            "vehicle_ID": vehicle_ID,
            "eclass": var_eclass,
            "CO2":var_CO2,
            "CO": var_CO,
            "HC": var_HC,
            "NOx": var_NOx,
            "PMx": var_PMx,
            "fuel": var_fuel,
            "electricity": var_electricity,
            "noise": var_noise,
            "route": var_route,
            "type": var_type,
            "waiting": var_waiting,
            "lane": var_lane,
            "pos": var_pos,
            "speed": var_speed,
            "angle": var_angle,
            "x": var_x,
            "y": var_y




        }, ignore_index=True)

print(df.head(40))
df.to_excel("/Users/emily/Desktop/emission_excel.xlsx")

#print(df.pos[:10])

"""
eclass="HBEFA3/PC_G_EU4"
CO2="2624.72"
CO="164.78"
HC="0.81"
NOx="1.20"
PMx="0.07"
fuel="1.13"
electricity="0.00"
noise="55.94"
route="!aggro.0!var#1"
type="aggro_car"
waiting="0.00"
lane="b29In_1"
pos="502.39"
speed="0.00"
angle="305.31"
x="7639.94"
y="3814.95"

"""